service: cognicity

# custom:

provider:
  name: aws
  profile: serverless
  runtime: nodejs6.10
  stage: ${opt:stage}
  region: ${file(./.env.yml):region}
  stackTags:
    area: ${file(./.env.yml):areatag}

package:
  individually: true
  exclude:
    - bin/functions/** # Include functions individually
    - bin/locales/**
    - bin/test/**
    - src/**
    - .git/**
    - .nyc_output/**
    - coverage/**
    - esdoc/**
    - .babelrc
    - .env
    - .eslintrc.js
    - .gitignore
    - .travis.yml
    - README.md

# Add one function for each Lambda
functions:
  # Whatsapp reports lambda (respond to user message)
  whatsapp-webhook:
    handler: bin/functions/webhook/index.handler
    package:
      include:
        - bin/functions/webhook/**
    environment:
      API_KEY: ${file(./.env.yml):${opt:stage}-api-key}
      CARDS_API: ${file(./.env.yml):${opt:stage}-cards-api}
      CARDS_API_KEY: ${file(./.env.yml):${opt:stage}-cards-api-key}
      CARDS_URL: ${file(./.env.yml):${opt:stage}-cards-url}
      DEFAULT_INSTANCE_REGION_CODE: ${file(./.env.yml):fallback-region}
      MAP_URL: ${file(./.env.yml):${opt:stage}-map-url}
      NETWORK_NAME: 'whatsapp'
      NETWORK_NUMBER: ${file(./.env.yml):whatsapp-number}
      TWILIO_ACCOUNT_SID: ${file(./.env.yml):account-sid}
      TWILIO_AUTH_TOKEN: ${file(./.env.yml):auth-token}
    # events:
    #   - http:
    #     path: whatsapp/webhook
    #     method: post

  # Whatsapp notify lambda (send report submission notification)
  whatsapp-send:
    handler: bin/functions/send/index.handler
    package:
      include:
        - bin/functions/send/**
    environment:
      API_KEY: ${file(./.env.yml):${opt:stage}-api-key}
      CARDS_API: ${file(./.env.yml):${opt:stage}-cards-api},
      CARDS_API_KEY: ${file(./.env.yml):${opt:stage}-cards-api-key}
      CARDS_URL: ${file(./.env.yml):${opt:stage}-cards-url}
      DEFAULT_INSTANCE_REGION_CODE: ${file(./.env.yml):fallback-region}
      MAP_URL: ${file(./.env.yml):${opt:stage}-map-url}
      NETWORK_NAME: 'whatsapp'
      NETWORK_NUMBER: ${file(./.env.yml):whatsapp-number}
      TWILIO_ACCOUNT_SID: ${file(./.env.yml):account-sid}
      TWILIO_AUTH_TOKEN: ${file(./.env.yml):auth-token}
    # SET LAMBDA INTEGRATION
    # events:
    #   - http:
    #     path: whatsapp/send
    #     method: post
    #     private: true

  # TODO: add twilio sms send & receive
